Handle Invalid Base64 tweaks somewhat
beyond-all-reason/BYAR-Chobby pull request #791
Opened 2024-10-30 11:10 UTC by robertthepie

Try Catches attempts at decoding invalid base64 strings within tweakdefs and tweakunits

## Test steps:

Set either of the tweak fields to: `a`
- The preview field without this change will not update
- With this change it will show it as Invalid, considering making it say `May be Invalid` instead?

## Screenshots

![image](https://github.com/user-attachments/assets/c860a711-3fb9-4ddd-aca0-11713cbc1f4f)

2024-10-30 12:15 UTC, Beherith requested changes
Please disambiguate boolean operator order of ... and ... or ... with parenthesis
If pcalling, please use the return error as an indicator for the user
success is double the C, double the S

2024-10-30 12:32 UTC, ryanbennitt commented
Should the text "Invalid" come from translation? e.g. i18n("invalid") assuming "invalid" en/de entries are added to i18n/chililobby.lua

2024-10-30 12:35 UTC, robertthepie commented
I believe attempting to support translation in chobby is half abbandonded, all over the place, and probably not worth it as it is to be replaced with the new lobby

> Please disambiguate boolean operator order of ... and ... or ... with parenthesis

i don't know how to do that with valid syntax

> If pcalling, please use the return error as an indicator for the user

what do i give them? `Invalid Base64`? the error message isn't game, it's just the attempt at giving some preview, typically a comment on line 1 of the tweak giving it's name/purpose

2024-10-31 14:57 UTC, robertthepie commented
Updated it somewhat to:

- allow users to fake unset string modoptions
- tell users that the base64 couldn't be parsed, in the changed modoptions preview panel

but i am just a silly little guy

2024-10-31 15:15 UTC, robertthepie commented
*this doesn't work as the game can't handle invalid base 64

2024-11-07 19:21 UTC, drivver44 commented
i have tested this PR 
i do get the expected behavior.

i have only tested this pr, with no code review.

2024-11-14 20:07 UTC, WatchTheFort approved these changes

2024-11-14 20:09 UTC, merged